### ISSUE TITLE
Använd config

### ISSUE THREAD

**Issue by JohanG2012** [JSudden/MVC-Lir#3]
https://github.com/JSudden/MVC-Lir/blob/f9828c868707dd64e17e1fe0b48da90c084f90d0/app/views/includes/navbar.php#L9-L12

**Comment by JSudden** [comment]
Tips monster kostar 10kr på coop konsum

**Comment by JohanG2012** [comment]
Vilken av alla konsum? :smile:

**Comment by JSudden** [comment]
Den vid Ludvika gård :smile:

**Comment by JohanG2012** [comment]
Nice!
